# Logistic Regression

- 붓꽃 품종 예측
- scikit-learn 에서 dataset을 제공

In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

- type이 numpy라서 numpy 라이브러리 가져와서 사용

In [8]:
import numpy as np
np.unique(y)

array([0, 1, 2])

### train, test 로 분리

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (38, 4), (112,), (38,))

In [16]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train, y_train)

LogisticRegression()

In [17]:
log.coef_, log.intercept_

(array([[-0.41830233,  0.86394458, -2.36198183, -0.94602932],
        [ 0.65658694, -0.26146764, -0.2117445 , -0.89484484],
        [-0.23828461, -0.60247694,  2.57372632,  1.84087416]]),
 array([  9.38766394,   1.09391775, -10.48158169]))

In [18]:
log.predict_proba(x_train[:4])

array([[2.15421969e-02, 9.43340184e-01, 3.51176191e-02],
       [1.43385558e-03, 7.40642887e-01, 2.57923258e-01],
       [1.05384318e-04, 1.81245502e-01, 8.18649114e-01],
       [7.65424813e-02, 9.17737985e-01, 5.71953387e-03]])

In [19]:
log.predict(x_train[:4])

array([1, 1, 2, 1])

In [20]:
from sklearn import metrics

In [24]:
y_pred = log.predict(x_test)
y_pred.shape, y_test.shape

((38,), (38,))

In [25]:
y_pred

array([0, 2, 2, 0, 2, 1, 2, 0, 2, 0, 1, 2, 1, 1, 0, 2, 2, 1, 2, 1, 0, 0,
       0, 2, 0, 2, 1, 2, 1, 1, 2, 0, 2, 2, 0, 0, 2, 0])

In [26]:
y_test

array([0, 2, 2, 0, 2, 1, 2, 0, 2, 0, 1, 2, 1, 1, 0, 2, 2, 1, 2, 1, 0, 0,
       0, 1, 0, 1, 1, 2, 1, 1, 2, 0, 2, 2, 0, 0, 2, 0])

In [28]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.82      0.90        11
           2       0.88      1.00      0.93        14

    accuracy                           0.95        38
   macro avg       0.96      0.94      0.94        38
weighted avg       0.95      0.95      0.95        38



## 분류 성능 평가

- 참조: https://datascienceschool.net/03%20machine%20learning/09.04%20%EB%B6%84%EB%A5%98%20%EC%84%B1%EB%8A%A5%ED%8F%89%EA%B0%80.html
![ML06_02_01.JPG](./lecture_imgs/ML06_02_01.JPG)

In [29]:
metrics.confusion_matrix(y_test, y_pred)

array([[13,  0,  0],
       [ 0,  9,  2],
       [ 0,  0, 14]], dtype=int64)